/**
 * Image Exam Categories for Imagenology Request Form
 */

export interface ImageExamCategory {
    id: string;
    name: string;
    exams: string[];
}

export const RADIOLOGY_EXAMS: ImageExamCategory = {
    id: 'radiology',
    name: 'RADIOLÓGICOS SIMPLES',
    exams: [
        'CAVUM RINOFARINGE', 'CAVIDADES PERINASALES', 'CODO AP-LAT', 'EDAD ÓSEA',
        'HUESOS PROPIOS NASALES', 'ANTEBRAZO AP-LAT', 'TÓRAX SIMPLE', 'ÓRBITA / MALAR / ATM',
        'MUÑECA AP-LAT', 'TÓRAX AP-LAT', 'CRÁNEO AP-LAT', 'MANO AP-OBL',
        'ABDOMEN SIMPLE', 'CRÁNEO TOWNE', 'ESTUDIO DE ESCAFOIDES', 'RENAL SIMPLE',
        'PELVIS AP / CADERA AP', 'DEDO AP-LAT-OBL', 'VESICAL SIMPLE', 'PELVIS INLET-OUTLET / PELVIS LOWENSTEIN',
        'FÉMUR AP-LAT', 'COL. CERVICAL AP-LAT', 'CADERA AXIAL / CADERA ALAR-OBTURATRIZ / OTROS',
        'RODILLA AP-LAT', 'COL. CERVICAL OBLICUAS', 'SACROCOXIS / ART.SACROILIACAS', 'RÓTULA AXIAL',
        'COL. CERVICAL FUNCIONALES', 'HOMBRO AP-AXIAL', 'TÚNEL INTERCONDILEO / ROSSEMBERG',
        'COL. DORSAL AP-LAT', 'HOMBRO OUTLET / HOMBRO ROTACIONES / OTROS', 'PIERNA AP-LAT',
        'COL. LUMBAR AP-LAT-5°ESPACIO', 'ESCÁPULA AP-LAT', 'TOBILLO AP-LAT-OBL',
        'COL. LUMBAR OBLICUAS', 'CLAVÍCULA AP-AXIAL', 'PIE AP-OBL',
        'COL. LUMBAR FUNCIONALES', 'ART. ACROMIOCLAVICULAR', 'PIES CON CARGA',
        'PARRILLA COSTAL AP-OBL', 'HÚMERO AP-LAT'
    ]
};

export const SCANNER_EXAMS: ImageExamCategory = {
    id: 'scanner',
    name: 'SCANNER (TAC)',
    exams: [
        'CEREBRO', 'CPN / ÓRBITA / MAXILOFACIAL', 'OÍDO', 'CUELLO', 'TÓRAX',
        'ABDOMEN', 'PELVIS', 'COL. CERVICAL (5 VERT. - 4 ESPACIOS)',
        'COL. DORSAL (4 VERT. - 3 ESPACIOS)', 'COL. LUMBAR (4 VERT. - 3 ESPACIOS)',
        'COLUMNA ESPACIO ADICIONAL', 'PIELOTAC', 'UROTAC', 'ANGIOTAC'
    ]
};

export const ULTRASOUND_EXAMS: ImageExamCategory = {
    id: 'ultrasound',
    name: 'ECOGRAFÍA',
    exams: [
        'ECO ABDOMINAL', 'ECO GINECOLOGICA', 'ECO MAMARIA', 'ECO MUSCULOESQUELETICA',
        'ECO OBSTÉTRICA', 'ECO PARTES BLANDAS', 'ECO RENAL', 'ECO TESTICULAR',
        'ECO TIROIDEA', 'ECO VESICOPROSTÁTICA', 'ECO PELVIS', 'ECO DOPPLER'
    ]
};

export const IMAGE_EXAM_CATEGORIES: ImageExamCategory[] = [
    RADIOLOGY_EXAMS,
    SCANNER_EXAMS,
    ULTRASOUND_EXAMS
];
