const BACKEND_RUNTIME_CONTRACT_VERSION = 1;
const MIN_SUPPORTED_CLIENT_RUNTIME_CONTRACT_VERSION = 1;
const SUPPORTED_SCHEMA_VERSION = 1;
const LEGACY_SCHEMA_FLOOR_VERSION = 0;

module.exports = {
  BACKEND_RUNTIME_CONTRACT_VERSION,
  MIN_SUPPORTED_CLIENT_RUNTIME_CONTRACT_VERSION,
  SUPPORTED_SCHEMA_VERSION,
  LEGACY_SCHEMA_FLOOR_VERSION,
};
